language: node_js

node_js:
  - "9"

services:
  - mysql
  - postgresql

install:
 - npm i
 - npm i -g codeclimate-test-reporter

script:
 - npm run test:coverage

notifications:
  email: false