language: node_js

node_js:
  - "9"

install:
 - npm i
 - npm i -g codeclimate-test-reporter

 services:
  - mysql
  - postgresql

script:
 - npm run test:coverage

notifications:
  email: false